---
- name: Install git
  apt:
    name: git

- name: Check required variables
  ansible.builtin.debug:
    msg: host owned by user {{ full_name }} with account {{ local_user }} and email {{ email }}

- name: Configure system-wide git email
  community.general.git_config:
    name: user.email
    value: '{{ email }}'

- name: Configure system-wide git user name
  community.general.git_config:
    name: user.name
    value: '{{ full_name }}'
